name: Publish to Docker Hub
on:
    push:
        tags:
            - '*'
        branches:
            - 'main'
env:
    DOCKER_HUB_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Docker Hub Login
              run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_TOKEN}}
            - name: Build Image
              run: docker build -t lastcallmedia/terminus-safe-deploy:${{ env.DOCKER_HUB_TAG }} --build-arg plugin_tag=${{ github.ref_name }} .
            - name: Push Image
              run: docker push lastcallmedia/terminus-safe-deploy:${{ env.DOCKER_HUB_TAG }}
